#!/usr/bin/env sh

mariadb -u root -p"$WP_ADMIN_PASS" << EOF
CREATE DATABASE IF NOT EXISTS $WP_DATABASE;
CREATE USER '$WP_ADMIN_USER'@'%' IDENTIFIED BY '$WP_ADMIN_PASS';
GRANT ALL ON $WP_DATABASE.* TO '$WP_ADMIN_USER'@'%';
FLUSH PRIVILEGES;
EOF